# ============================================================================
# This file contains configuration flags to customize your site
# ============================================================================
# 1. Site Metadata
# 2. Site Navigation
# 3. Social Menu
# 4. Google AdSense
# 5. Google Analytics
# ============================================================================


# ----------------------------------------------------------------------------
# 1. Site Metadata (all fields mandatory)
# ----------------------------------------------------------------------------

# Your site's title
title:                     Simple Material

# A short description
tagline:                   Less is More

# A longer description used for the description meta tag
description:               Simple Material is a Jekyll theme for blogs and portfolios. Designed with Google's Material Design guidelines in mind, it provides a a beautiful, clean and mobile-first fully-responsive interface for building your new website with minimal code.

# Name of the author
author:                    John Doe

# For showing Twitter cards
twitter:
  username: saifkhichi96
  card: summary

# URL of your avatar or profile pic (you could use your GitHub profile pic)
logo:                      /assets/images/logo.png

# For specifying social profiles
social:
  name: Muhammad Saif Ullah Khan
  links:
    - https://twitter.com/saifkhichi96
    - https://www.linkedin.com/in/saifkhichi96
    - https://github.com/saifkhichi96

# For verifying ownership via Google Search Console (https://cloud.google.com/identity/docs/verify-domain-web)
# google_site_verification:

# Manifest and favicon
manifest:                  /manifest.json
favicon:                   /favicon.ico

# Your site language code (see: https://www.w3schools.com/tags/ref_language_codes.asp)
lang:                      en-US

# If you're hosting your GitHub pages site at your User repository
# (http://yourusername.github.io), leave baseurl empty: "", OR if you're hosting
# it at a Project repo instead (http://yourusername.github.io/repository-name)
# then set the baseurl to: "/repository-name"
baseurl:                   ""

# Your website URL (e.g. http://yourusername.github.io or http://www.domain.com)
# Used for Sitemap.xml and your RSS feed
url:                       http://www.saifkhichi.com/simple-material/
enforce_ssl:               https://www.saifkhichi.com/simple-material/


# ----------------------------------------------------------------------------
# Services
# ----------------------------------------------------------------------------
services:
- title:                   Service 1
  description:             Lorem ipsum dolor sit amet, consectetur adipiscing elit.
  icon:                    cleaning_services
- title:                   Service 2
  description:             Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.
  icon:                    dry_cleaning
- title:                   Service 3
  description:             Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.
  icon:                    local_laundry_service
- title:                   Service 4
  description:             Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur.
  icon:                    design_services

skills:
  - type:                  Skillset 1
    items:
      - name:              Skill 1-1
      - name:              Skill 1-2
      - name:              Skill 1-3
      - name:              Skill 1-4

  - type:                  Skillset 2
    items:
      - name:              Skill 2-1
      - name:              Skill 2-2
      - name:              Skill 2-3

  - type:                  Skillset 3
    items:
      - name:              Skill 3-1
      - name:              Skill 3-2
      - name:              Skill 3-3
      - name:              Skill 3-4
      - name:              Skill 3-5

spoken_languages:
- name:                    Language 1
  proficiency:             Bilingual
- name:                    Language 2
  proficiency:             Basic
- name:                    Language 3
  proficiency:             Native

interests:
- name:                    Interest 1
  description:             Lorem ipsum dolor sit amet.
  url:                     /more/about/interest/1
- name:                    Interest 2
  description:             Lorem ipsum dolor sit amet.
  url:                     /more/about/interest/2

experience:
- institute:               Company
  location:                Location
  position:                Position
  time:                    2016 - present
  type:                    1
  url:                     /more/about/job/
- institute:               University
  location:                Location
  position:                Name of Degree
  time:                    2014 - 2016
  type:                    0
  url:                     /more/about/degree/
  details:
    title:                 Specializations
    items:
      - name:              Specialization 1
        description:
      - name:              Specialization 2
        description:
- institute:               College
  location:                Location
  position:                Name of Degree
  score:                   4.0 CGPA
  time:                    2010 - 2014
  type:                    0
  url:                     /more/about/degree/
  details:
    title:                 Co-Curricular Activities
    items:
      - name:              Activity 1
        description:       10/2012 - 02/2013<br>Lorem ipsum dolor sit amet.
      - name:              Activity 2
        description:       04/2011 - 07/2011<br>Lorem ipsum dolor sit amet.

# ----------------------------------------------------------------------------
# 1. Site Navigation (optional, can remove or leave fileds empty)
# ----------------------------------------------------------------------------

# Includes links in the sidebar (use icon names from https://material.io/icons/)
navigation_main:
- title:                   Home
  icon:                    home
  url:                     /
- title:                   Experience
  icon:                    work
  url:                     /resume/
- title:                   Projects
  icon:                    dashboard
  url:                     /projects/
- title:                   Services
  icon:                    extension
  url:                     /services/
- title:                   Contact
  icon:                    contact_support
  url:                     /contact/

navigation_footer:         true

# Includes an icon in the footer for each username you enter
footer-links:
  dribbble:
  email:                   saifkhichi96@gmail.com
  facebook:
  flickr:
  github:                  saifkhichi96
  instagram:               saifkhichi96
  linkedin:                saifkhichi96
  pinterest:
  rss:                     rss
  twitter:                 saifkhichi96
  stackoverflow:           4690466
  youtube:                 /channel/UCj4yPuKHi9pZ9WbKbfh5MEQ
  playconsole:             7722501168179136426

# Includes links to your site's privacy policy and terms of service in the footer
privacy:                   "/privacy/"
terms:                     "/tos/"


# Enter your Disqus shortname (not your username) to enable commenting on posts
# You can find your shortname on the Settings page of your Disqus account
disqus:                    saifkhichi

# Enter your Google AdSense ad client code (e.g. ca-pub-XXXXXXXXXXXXXXXX) to activate Ads
google_adsense:            ca-pub-6293532072634065

# Enter your Google Analytics web tracking code (e.g. UA-2110908-2) to activate tracking
# google_analytics:        UA-43339302-11

# For newer "GA4" analytics, use the following instead of the "UA" entry above
# google_analytics_ga4:    G-GABC1DEFG

#
# !! You don't need to change any of the configuration flags below !!
#

permalink:                 /:title/

# The release of Jekyll Now that you're using
version:                   v1.0.0

# Jekyll 3 now only supports Kramdown for Markdown
kramdown:
  # Use GitHub flavored markdown, including triple backtick fenced code blocks
  input:                   GFM

# Set the Sass partials directory, as we're using @imports
sass:
  style:                   :compressed # You might prefer not to minify using :expanded

# Use the following plug-ins
plugins:
  - jekyll-sitemap  # Create a sitemap using the official Jekyll sitemap gem
  - jekyll-feed     # Create an Atom feed using the official Jekyll feed gem
  - jekyll-seo-tag
  - jekyll-paginate
  - jekyll-paginate-v2

include:                   ['_pages']

collections:
  projects:
    output:                true
    permalink:             /projects/:path/

pagination:
  enabled:                 true
  per_page:                10
  permalink:               /:num/
  sort_reverse:            true
  sort_field:              'date'
  title:                   ':title'
  trail:
    before:                2
    after:                 2

# Exclude these files from your production _site
exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
